// Auto-generated by Style Dictionary. Do not edit.
package com.picke.presentation.ui.theme.tokens

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object ComponentNumberTokens {
    val iconXs: Dp = 12.dp
    val iconSm: Dp = 16.dp
    val iconMd: Dp = 20.dp
    val iconLg: Dp = 24.dp
    val avatarSm: Dp = 36.dp
    val avatarMd: Dp = 40.dp
    val avatarLg: Dp = 68.dp
    val controlSm: Dp = 28.dp
    val controlMd: Dp = 52.dp
    val gap0: Dp = 0.dp
    val gap2: Dp = 2.dp
    val gap4: Dp = 4.dp
    val gap6: Dp = 6.dp
    val gap8: Dp = 8.dp
    val gap12: Dp = 12.dp
    val gap16: Dp = 16.dp
    val gap20: Dp = 20.dp
    val gap24: Dp = 24.dp
    val gap32: Dp = 32.dp
    val gap40: Dp = 40.dp
    val paddingScreenHorizontal: Dp = 16.dp
    val paddingContainer8: Dp = 8.dp
    val paddingContainer12: Dp = 12.dp
    val paddingContainer16: Dp = 16.dp
    val paddingContainer20: Dp = 20.dp
    val paddingContainer24: Dp = 24.dp
    val paddingContainer32: Dp = 32.dp
    val paddingContainer40: Dp = 40.dp
    val paddingComponent2: Dp = 2.dp
    val paddingComponent4: Dp = 4.dp
    val paddingComponent6: Dp = 6.dp
    val paddingComponent8: Dp = 8.dp
    val paddingComponent12: Dp = 12.dp
    val paddingComponent16: Dp = 16.dp
    val paddingButtonPrimaryLargeHorizontal: Dp = 12.dp
    val paddingButtonPrimaryLargeVertical: Dp = 12.dp
    val paddingButtonPrimaryMediumHorizontal: Dp = 12.dp
    val paddingButtonPrimaryMediumVertical: Dp = 12.dp
    val paddingButtonPrimarySmallHorizontal: Dp = 12.dp
    val paddingButtonPrimarySmallVertical: Dp = 12.dp
    val paddingChipHorizontal: Dp = 12.dp
    val paddingChipVertical: Dp = 6.dp
    val paddingBadgeHorizontal: Dp = 6.dp
    val paddingBadgeVertical: Dp = 2.dp
    val paddingCardBase: Dp = 16.dp
    val paddingInputHorizontal: Dp = 8.dp
    val paddingNavigationTabHorizontal: Dp = 12.dp
    val paddingNavigationTabVertical: Dp = 12.dp
    val paddingAppbarHorizontal: Dp = 16.dp
    val paddingAppbarVertical: Dp = 12.dp
    val borderWidthRegular: Dp = 1.dp
    val borderWidthMedium: Dp = 1.5.dp
    val borderWidthLarge: Dp = 4.dp
    val buttonPrimaryLargeWidth: Dp = 343.dp
    val buttonPrimaryLargeHeight: Dp = 52.dp
    val buttonPrimaryMediumWidth: Dp = 343.dp
    val buttonPrimaryMediumHeight: Dp = 42.dp
    val buttonPrimarySmallWidth: Dp = 100.dp
    val buttonPrimarySmallHeight: Dp = 42.dp
    val buttonIconSize: Dp = 36.dp
    val toggleThumbSize: Dp = 14.dp
    val toggleWidth: Dp = 32.dp
    val toggleHeight: Dp = 18.dp
    val cardAvatarMd: Dp = 40.dp
    val cardAvatarLg: Dp = 68.dp
    val cardAvatarSm: Dp = 36.dp
    val inputTextfieldWidth: Dp = 343.dp
    val inputTextfieldHeight: Dp = 44.dp
    val popupWidth: Dp = 393.dp
    val thumbnailWidth: Dp = 196.dp
    val thumbnailHeight: Dp = 140.dp
    val checkboxWidth: Dp = 24.dp
    val checkboxHeight: Dp = 24.dp
}
