// Auto-generated by Style Dictionary. Do not edit.
package com.picke.presentation.ui.theme.tokens

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object
ComponentNumberTokens {
    val buttonRadius: Dp = 2.dp
}
