// Auto-generated by Style Dictionary. Do not edit.
package com.picke.presentation.ui.theme.tokens

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object RadiusTokens {
    val default: Dp = 2.dp
    val max: Dp = 999.dp
}
